sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t aristov81/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true aristov81/docker-react npm run test -- --coverage
